language: java
env:
  - MAVEN_TEMP=MAVEN_TEMP
cache:
  directories:
    - "$HOME/.m2/repository"
dist: xenial
sudo: required
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V;
script: mvn test;
jdk:
  - oraclejdk11
after_success:
  - mvn clean cobertura:cobertura coveralls:report
notification:
  slack: jackalsin-personal:qozHNsKCv2gavUKGDM5LOMcf
  email:
    on_success: never
    on_failure: always